// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_likelihood
arma::vec rcpp_likelihood(const arma::imat mEM, const int nIntNodes, const arma::imat mAli, const int nStates, NumericVector vProb, const arma::rowvec vPi, const bool takeLog);
RcppExport SEXP lyne_rcpp_likelihood(SEXP mEMSEXP, SEXP nIntNodesSEXP, SEXP mAliSEXP, SEXP nStatesSEXP, SEXP vProbSEXP, SEXP vPiSEXP, SEXP takeLogSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::imat >::type mEM(mEMSEXP);
    Rcpp::traits::input_parameter< const int >::type nIntNodes(nIntNodesSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type mAli(mAliSEXP);
    Rcpp::traits::input_parameter< const int >::type nStates(nStatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vProb(vProbSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type vPi(vPiSEXP);
    Rcpp::traits::input_parameter< const bool >::type takeLog(takeLogSEXP);
    __result = Rcpp::wrap(rcpp_likelihood(mEM, nIntNodes, mAli, nStates, vProb, vPi, takeLog));
    return __result;
END_RCPP
}
