# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_likelihood <- function(mEM, nIntNodes, mAli, nStates, vProb, vPi, takeLog) {
    .Call('lyne_rcpp_likelihood', PACKAGE = 'lyne', mEM, nIntNodes, mAli, nStates, vProb, vPi, takeLog)
}

